-- SQL Schema Generated by NoSQL-to-SQL Migration Tool
-- Generated on: 2026-01-15 09:45:42
-- Main Table: bestellingen
-- Total Tables: 1

-- ═══════════════════════════════════════════════════════

-- Drop table if exists
IF OBJECT_ID('bestellingen', 'U') IS NOT NULL DROP TABLE bestellingen;

-- Main table: bestellingen
CREATE TABLE bestellingen (
    [_id] VARCHAR(24) PRIMARY KEY NOT NULL,
    [aantal] INT NOT NULL,
    [datum] DATETIME2 NOT NULL,
    [klantId] VARCHAR(24) NOT NULL,
    [product] VARCHAR(255) NOT NULL
);


