-- SQL Schema Generated by NoSQL-to-SQL Migration Tool
-- Generated on: 2026-01-15 09:45:41
-- Main Table: producten
-- Total Tables: 1

-- ═══════════════════════════════════════════════════════

-- Drop table if exists
IF OBJECT_ID('producten', 'U') IS NOT NULL DROP TABLE producten;

-- Main table: producten
CREATE TABLE producten (
    [_id] VARCHAR(24) PRIMARY KEY NOT NULL,
    [naam] VARCHAR(255) NOT NULL,
    [prijs] DECIMAL(18,2) NOT NULL,
    [voorraad] INT NOT NULL
);


