-- SQL Schema Generated by NoSQL-to-SQL Migration Tool
-- Generated on: 2026-01-15 09:44:34
-- Main Table: klanten
-- Total Tables: 1

-- ═══════════════════════════════════════════════════════

-- Drop table if exists
IF OBJECT_ID('klanten', 'U') IS NOT NULL DROP TABLE klanten;

-- Main table: klanten
CREATE TABLE klanten (
    [_id] VARCHAR(24) PRIMARY KEY NOT NULL,
    [email] VARCHAR(255) NOT NULL,
    [leeftijd] INT NOT NULL,
    [naam] VARCHAR(255) NOT NULL,
    [stad] VARCHAR(255) NOT NULL
);


